INSERT INTO movies (adult, backdrop_path, genre_ids, id, original_language, original_title, overview, popularity, poster_path, release_date, title, video, vote_average, vote_count)
VALUES
(""false"","/8s4h9friP6Ci3adRGahHARVd76E.jpg",[16,35,10751,878],379686,"en","Space Jam: A New Legacy","When LeBron and his young son Dom are trapped in a digital space by a rogue A.I., LeBron must get them home safe by leading Bugs, Lola Bunny and the whole gang of notoriously undisciplined Looney Tunes to victory over the A.I.'s digitized champions on the court. It's Tunes versus Goons in the highest-stakes challenge of his life.",7153.206,"/5bFK5d3mVTAvBCXi5NPWH0tYjKl.jpg","2021-07-08","Space Jam: A New Legacy",""false"","7.8","1230"),

("false","/keIxh0wPr2Ymj0Btjh4gW7JJ89e.jpg",[28,12,53,878],497698,"en","Black Widow","Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.",5750.009,"/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg","2021-07-07","Black Widow","false",8,3337),

("false","/tehpKMsls621GT9WUQie2Ft6LmP.jpg",[12,53,28,27,37],602223,"en","The Forever Purge","All the rules are broken as a sect of lawless marauders decides that the annual Purge does not stop at daybreak and instead should never end as they chase a group of immigrants who they want to punish because of their harsh historical past.",5616.37,"/uHA5COgDzcxjpYSHHulrKVl6ByL.jpg","2021-06-30","The Forever Purge","false",7.8,577),

("false","/gX5UrH1TLVVBwI7WxplW43BD6Z1.jpg",[16,35,12,10751],459151,"en","The Boss Baby: Family Business","The Templeton brothers — Tim and his Boss Baby little bro Ted — have become adults and drifted away from each other. But a new boss baby with a cutting-edge approach and a can-do attitude is about to bring them together again … and inspire a new family business.",4263.831,"/5dExO5G2iaaTxYnLIFKLWofDzyI.jpg","2021-07-01","The Boss Baby: Family Business","false",7.9,894),

("false","/yizL4cEKsVvl17Wc1mGEIrQtM2F.jpg",[28,878],588228,"en","The Tomorrow War","The world is stunned when a group of time travelers arrive from the year 2051 to deliver an urgent message: Thirty years in the future, mankind is losing a global war against a deadly alien species. The only hope for survival is for soldiers and civilians from the present to be transported to the future and join the fight. Among those recruited is high school teacher and family man Dan Forester. Determined to save the world for his young daughter, Dan teams up with a brilliant scientist and his estranged father in a desperate quest to rewrite the fate of the planet.",3297.608,"/34nDCQZwaEvsy4CFO5hkGRFDCVU.jpg","2021-06-30","The Tomorrow War","false",8.3,2884),

("false","/620hnMVLu6RSZW6a5rwO8gqpt0t.jpg",[16,35,10751,14],508943,"en","Luca","Luca and his best friend Alberto experience an unforgettable summer on the Italian Riviera. But all the fun is threatened by a deeply-held secret: they are sea monsters from another world just below the water’s surface.",2966.59,"/jTswp6KyDYKtvC52GbHagrZbGvD.jpg","2021-06-17","Luca","false",8.1,3226),

("false","/wjQXZTlFM3PVEUmKf1sUajjygqT.jpg",[878,28,53],581726,"en","Infinite","Evan McCauley has skills he never learned and memories of places he has never visited. Self-medicated and on the brink of a mental breakdown, a secret group that call themselves “Infinites” come to his rescue, revealing that his memories are real.",2350.156,"/niw2AKHz6XmwiRMLWaoyAOAti0G.jpg","2021-06-10","Infinite","false",7.2,542),

("false","/3RMbkXS4ocMmoJyAD3ZsWbm32Kx.jpg",[28,12,18,878,53],615658,"en","Awake","After a sudden global event wipes out all electronics and takes away humankind’s ability to sleep, chaos quickly begins to consume the world. Only Jill, an ex-soldier with a troubled past, may hold the key to a cure in the form of her own daughter. The question is, can Jill safely deliver her daughter and save the world before she herself loses her mind.",2327.953,"/uZkNbB8isWXHMDNoIbqXvmslBMC.jpg","2021-06-09","Awake","false",6.1,550),

("false","/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg",[28,12,80,53],385128,"en","F9","Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.",1923.049,"/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg","2021-05-19","F9","false",7.5,731),

("false","/70AV2Xx5FQYj20labp0EGdbjI6E.jpg",[80,28,53],637649,"en","Wrath of Man","A cold and mysterious new security guard for a Los Angeles cash truck company surprises his co-workers when he unleashes precision skills during a heist. The crew is left wondering who he is and where he came from. Soon, the marksman's ultimate motive becomes clear as he takes dramatic and irrevocable steps to settle a score.",1903.109,"/M7SUK85sKjaStg4TKhlAVyGlz3.jpg","2021-04-22","Wrath of Man","false",7.9,1560),

("false","/6MKr3KgOLmzOP6MSuZERO41Lpkt.jpg",[35,80],337404,"en","Cruella","In 1970s London amidst the punk rock revolution, a young grifter named Estella is determined to make a name for herself with her designs. She befriends a pair of young thieves who appreciate her appetite for mischief, and together they are able to build a life for themselves on the London streets. One day, Estella’s flair for fashion catches the eye of the Baroness von Hellman, a fashion legend who is devastatingly chic and terrifyingly haute. But their relationship sets in motion a course of events and revelations that will cause Estella to embrace her wicked side and become the raucous, fashionable and revenge-bent Cruella.",1756.111,"/rTh4K5uw9HypmpGslcKd4QfHl93.jpg","2021-05-26","Cruella","false",8.4,4349),

("false","/zsH3iW60T1t2HBTtrSKzzxJ406J.jpg",[16,35,10751],846214,"en","The Simpsons: The Good, the Bart, and the Loki","Loki is banished from Asgard once again and must face his toughest opponents yet: the Simpsons and Springfield’s mightiest heroes. The God of Mischief teams up with Bart Simpson in the ultimate crossover event paying tribute to the Marvel Cinematic Universe of superheroes and villains.",1664.683,"/jZiSWDKNceZ90KQlFfkx6Tud3Pv.jpg","2021-07-07","The Simpsons: The Good, the Bart, and the Loki","false",8,295),

("false","/x9p2syPxeK2OYCpz35fsg0EFjlG.jpg",[16,35],834404,"en","Teen Titans Go! See Space Jam","The Teen Titans are visited by the Nerdlucks, the Space Jam villains who tried to capture Michael Jordan and the Looney Tunes. Astonished to discover his fellow Titans have never seen Space Jam, Cyborg organizes an exclusive watch party. Of course, if the Titans are watching a movie, don't expect silence to be golden. Raven and Starfire provide the commentary, Cyborg presents the fun facts, Beast Boy points out the butt shots, and Robin, but Robin doesn't trust their new alien friends. Are the Nerdlucks here to attend an innocent watch party, or do they have more sinister motives up their sleeves?",1643.381,"/rMoVOCw6DF3zC6hS76ZhQMWiXNX.jpg","2021-06-20","Teen Titans Go! See Space Jam","false",7.3,66),

("false","/5HjzYTihkH7EvOWSE7KcsF6pBMM.jpg",[10751,35,12,16,14],522478,"en","Peter Rabbit 2: The Runaway","Bea, Thomas, and the rabbits have created a makeshift family, but despite his best efforts, Peter can’t seem to shake his mischievous reputation. Adventuring out of the garden, Peter finds himself in a world where his mischief is appreciated, but when his family risks everything to come looking for him, Peter must figure out what kind of bunny he wants to be.",1617.292,"/cycDz68DtTjJrDJ1fV8EBq2Xdpb.jpg","2021-03-25","Peter Rabbit 2: The Runaway","false",7.3,202),

("false","/AsqUSUqXrK8JfH8WEQnCXVbIAv6.jpg",[878,53,27],520763,"en","A Quiet Place Part II","Following the events at home, the Abbott family now face the terrors of the outside world. Forced to venture into the unknown, they realize that the creatures that hunt by sound are not the only threats that lurk beyond the sand path.",1448.823,"/4q2hz2m8hubgvijz8Ez0T2Os2Yv.jpg","2021-05-21","A Quiet Place Part II","false",7.7,2165),

("false","/iJ2HVOZT9Kjayrhy21pbGIJs9ey.jpg",[28,12,14],525660,"cn","真·三国无双","Warlords, warriors and statesmen wage a battle for supremacy in this fantasy tale based on the hit video games and the \"Romance of the Three Kingdoms.\"",1432.416,"/7BCTdek5LFHglcgl7shsm7igJAH.jpg","2021-04-29","Dynasty Warriors","false",6.5,42),

("false","/ok7RdHhVngnwkvKj09tvtOvypG.jpg",[80,18,53,9648],649409,"en","No Sudden Move","A group of criminals are brought together under mysterious circumstances and have to work together to uncover what's really going on when their simple job goes completely sideways.",1296.452,"/34BmdJkdvRweC3xJJFlOFQ2IbYc.jpg","2021-06-24","No Sudden Move","false",6.6,128),

("false","/c0izdYdnTe4uMRifHgvTA85wPz0.jpg",[28,80,27],503736,"en","Army of the Dead","Following a zombie outbreak in Las Vegas, a group of mercenaries take the ultimate gamble: venturing into the quarantine zone to pull off the greatest heist ever attempted.",1207.08,"/z8CExJekGrEThbpMXAmCFvvgoJR.jpg","2021-05-14","Army of the Dead","false",6.4,2010),

("false","/qi6Edc1OPcyENecGtz8TF0DUr9e.jpg",[27,9648,53],423108,"en","The Conjuring: The Devil Made Me Do It","Paranormal investigators Ed and Lorraine Warren encounter what would become one of the most sensational cases from their files. The fight for the soul of a young boy takes them beyond anything they'd ever seen before, to mark the first time in U.S. history that a murder suspect would claim demonic possession as a defense.",1094.102,"/xbSuFiJbbBWCkyCCKIMfuDCA4yV.jpg","2021-05-25","The Conjuring: The Devil Made Me Do It","false",7.9,3209),

("false","/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg",[28,14,12],460465,"en","Mortal Kombat","Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.",1077.922,"/nkayOAUBUu4mMvyNf9iHSUiPjF1.jpg","2021-04-07","Mortal Kombat","false",7.5,3381)